<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//debug mail
$config['development_mail'] = 'honma@zeus.corp.813.co.jp';
$config['testing_mail']     = 'keiichi-honma@813.co.jp';

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']    = '';
$config['lang_base_url']    = '';

/*
|--------------------------------------------------------------------------
| show message settings
|
| 'show_message_url' = show message url.
|--------------------------------------------------------------------------
*/
$config['show_message_url'] = 'user/message';
$config['show_message_cart_url'] = 'cart/message';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'            Default - auto detects
| 'PATH_INFO'        Uses the PATH_INFO
| 'QUERY_STRING'    Uses the QUERY_STRING
| 'REQUEST_URI'        Uses the REQUEST_URI
| 'ORIG_PATH_INFO'    Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']    = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
// 国際化
$config['language'] = 'japanese';
$config['language_min'] = 'ja';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
//maintenance
$config['enable_hooks'] = FALSE; // フック機能を有効にする
$config['maintenance'] = FALSE; // メンテナンスモードを有効にする場合はTRUE
$config['maintenance_view'] = 'maintenance'; // メンテナンスモードで表示させるViewファイル

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']        = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']    = 'c';
$config['function_trigger']        = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|    0 = Disables logging, Error logging TURNED OFF
|    1 = Error Messages (including PHP errors)
|    2 = Debug Messages
|    3 = Informational Messages
|    4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'oia8e3e0ae0aowao90823a';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'        = the name you want for the cookie
| 'sess_expiration'            = the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'    = Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'        = Whether to encrypt the cookie
| 'sess_use_database'        = Whether to save the session data to a database
| 'sess_table_name'            = The name of the session database table
| 'sess_match_ip'            = Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'    = Whether to match the User Agent when reading the session data
| 'sess_time_to_update'        = how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']        = 'ci_session';
$config['sess_expiration']        = 86400;//default 7200
$config['sess_expire_on_close']    = TRUE;
$config['sess_encrypt_cookie']    = TRUE;
$config['sess_use_database']    = FALSE;
$config['sess_table_name']        = 'ci_sessions';
$config['sess_match_ip']        = FALSE;
$config['sess_match_useragent']    = TRUE;
$config['sess_time_to_update']    = 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']    = "";
$config['cookie_domain']    = "";
$config['cookie_path']        = "/";
$config['cookie_secure']    = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token_mirai_tenki';
$config['csrf_cookie_name'] = 'csrf_cookie_mirai_tenki';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';
$is_console = FALSE;
//if(in_array('console',explode('/',$_SERVER['PHP_SELF']))) $is_console = TRUE;
//var_dump($_SERVER['PHP_SELF']);//タイ環境だと動かない
if(isset($_SERVER['REQUEST_URI']) && in_array('console',explode('/',$_SERVER['REQUEST_URI']))) $is_console = TRUE;
/*
|--------------------------------------------------------------------------
| Dynamic CSS Setting
|--------------------------------------------------------------------------
|
*/
/*
|--------------------------------------------------------------------------
| Dynamic JS Setting
|--------------------------------------------------------------------------
|
*/
$config['stylesheets'][] = 'css/master.css';
$config['stylesheets'][] = 'css/jquery.sidr.dark.css';
$config['stylesheets'][] = 'css/jquery-ui-1.10.3.custom.css';
$config['javascripts'][] = 'js/jquery-1.7.2.min.js';
$config['javascripts'][] = 'js/css_browser_selector.js';
$config['javascripts'][] = 'js/jquery.sidr.min.js';
$config['javascripts'][] = 'http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js';
$config['javascripts'][] = 'http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js';
/*
|--------------------------------------------------------------------------
| Upload folder setting
|--------------------------------------------------------------------------
|
*/
$config['upload_folder_top'] = 'uploads';
$config['upload_temporary_folder'] = 'tmp';
$config['upload_comics_folder'] = 'comics';
$config['upload_profile_folder'] = 'profiles';

/*
|--------------------------------------------------------------------------
| Upload folder setting
|--------------------------------------------------------------------------
|
| EMERG   = 0;  // Emergency: system is unusable
| ALERT   = 1;  // Alert: action must be taken immediately
| CRIT    = 2;  // Critical: critical conditions
| ERR     = 3;  // Error: error conditions
| WARN    = 4;  // Warning: warning conditions
| NOTICE  = 5;  // Notice: normal but significant condition
| INFO    = 6;  // Informational: informational messages
| DEBUG   = 7;  // Debug: debug messages
|
*/
//$config['zend_log_filters'][] = 0;
//$config['zend_log_filters'][] = 1;
//$config['zend_log_filters'][] = 2;
//$config['zend_log_filters'][] = 3;
//$config['zend_log_filters'][] = 4;
//$config['zend_log_filters'][] = 5;
//$config['zend_log_filters'][] = 6;
//$config['zend_log_filters'][] = 7;
$config['zend_start_log_level'] = 7;
$config['zend_end_log_level'] = 0;
$config['zend_log_filename'] = APPPATH . 'logs/log-' . date( 'Y-m-d' ) . EXT;

/*
|--------------------------------------------------------------------------
| setting
|--------------------------------------------------------------------------
|
*/

$config['jma_weather_start_year'] = 1967;//1967から天気がある
//$config['jma_weather_start_year'] = 1993;//1993からを有効年とする

/*
|--------------------------------------------------------------------------
| paging setting
|--------------------------------------------------------------------------
|
*/

$config['page_link_number'] = 5;
$config['paging_row_count'] = 3;
$config['paging_column_count'] = 3;
$config['paging_day_row_count'] = 7;
$config['paging_day_column_count'] = 3;
$config['paging_day_row_sp_count'] = 6;
$config['paging_day_column_sp_count'] = 1;


$config['paging_count_per_page'] = $config['paging_row_count'] * $config['paging_column_count'];
$config['paging_count_per_index_page'] = 9 * 7;//表示エリア数 × 7日間
$config['paging_count_per_recommend_page'] = $config['paging_day_row_count'] * $config['paging_day_column_count'];//7days 3つ
$config['paging_count_per_recommend_sp_page'] = $config['paging_day_row_sp_count'] * $config['paging_day_column_sp_count'];//6days 1つ
$config['paging_count_per_manage_page'] = 10;
/*
|--------------------------------------------------------------------------
| max min setting
|--------------------------------------------------------------------------
|
*/
$config['sp_display_number'] = 1;

$config['area_title_min_length'] = 1;
$config['area_title_max_length'] = 100;
$config['category_title_min_length'] = 1;
$config['category_title_max_length'] = 100;
$config['coupon_title_min_length'] = 1;
$config['coupon_title_max_length'] = 40;
$config['coupon_copy_min_length'] = 1;
$config['coupon_copy_max_length'] = 60;
$config['coupon_description_max_length'] = 1000;
$config['coupon_shop_max_length'] = 1000;
$config['coupon_address_max_length'] = 100;
$config['promotion_title_min_length'] = 1;
$config['promotion_title_max_length'] = 100;
$config['magazine_title_min_length'] = 1;
$config['magazine_title_max_length'] = 100;
$config['news_title_min_length'] = 1;
$config['news_title_max_length'] = 100;
$config['contact_description_max_length'] = 1000;
$config['cart_max_select_number'] = 30;

/*
|--------------------------------------------------------------------------
| allowed upload file type
|--------------------------------------------------------------------------
|
*/
$config['allowed_upload_file_type'] = 'gif|jpg|jpeg|png';

/*
|--------------------------------------------------------------------------
| upload coupon image setting
|--------------------------------------------------------------------------
|
*/
$config['upload_coupon_max_filesize'] = 20971520; // 20MB
$config['upload_coupon_image_max_filesize'] = 1024 * 1024; // file size byte (1MB)
$config['upload_coupon_image_allowed_types'] = array("image/gif", "image/jpg", "image/jpeg", "image/png");
$config['upload_coupon_image_min_width'] = 470;
$config['upload_coupon_image_min_height'] = 300;
$config['upload_coupon_image_max_width'] = 3000;
$config['upload_coupon_image_max_height'] = 4000;

/*
|--------------------------------------------------------------------------
| upload image setting
|--------------------------------------------------------------------------
|
*/
$config['upload_thumb_image_max_filesize'] = 1024 * 1024; // file size byte (1MB)
$config['upload_thumb_image_allowed_types'] = array("image/gif", "image/jpg", "image/jpeg", "image/png");
$config['upload_thumb_image_min_width'] = 230;
$config['upload_thumb_image_min_height'] = 200;
$config['upload_thumb_image_max_width'] = 3000;
$config['upload_thumb_image_max_height'] = 4000;
$config['upload_thumb_image_resize_width'] = 230;
$config['upload_thumb_image_resize_height'] = 200;

/*
|--------------------------------------------------------------------------
| upload html editor image setting
|--------------------------------------------------------------------------
|
*/
$config['upload_editor_max_filesize'] = 2097152; // 2MB
$config['upload_editor_image_max_filesize'] = 1024 * 1024; // file size byte (1MB)
$config['upload_editor_image_allowed_types'] = array("image/gif", "image/jpg", "image/jpeg", "image/png");
$config['upload_editor_image_min_width'] = 1;
$config['upload_editor_image_min_height'] = 1;
$config['upload_editor_image_max_width'] = 650;
$config['upload_editor_image_max_height'] = 650;

/*
|--------------------------------------------------------------------------
| tools setting
|--------------------------------------------------------------------------
|
*/

//$config['tools_magazine_span_time'] = 600;//1時間に1度チェックし、後ろ10分以内にあるメルマガを有効
$config['tools_magazine_span_time'] = 2400;//1時間に1度チェックし、後ろ40分以内にあるメルマガを有効

/*
|--------------------------------------------------------------------------
| api setting
|--------------------------------------------------------------------------
|
*/

$config['jalan_key'] = 'cap142351e1c1a';
$config['rakuten_key'] = '1013706927174899148';



$config['search_simple_area'] = array
(
    '9'=>'青森県',//青森
    '10'=>'秋田県',//秋田
    '11'=>'岩手県',//盛岡
    '12'=>'山形県',//山形
    '13'=>'宮城県',//仙台
    '14'=>'福島県',//福島
    '15'=>'新潟県',//新潟
    '16'=>'石川県',//金沢
    '17'=>'富山県',//富山
    '18'=>'長野県',//長野
    '19'=>'栃木県',//宇都宮
    '20'=>'福井県',//福井
    '21'=>'群馬県',//前橋
    '22'=>'埼玉県',//熊谷
    '23'=>'茨城県',//水戸
    '24'=>'岐阜県',//岐阜
    '25'=>'愛知県',//名古屋
    '26'=>'山梨県',//甲府
    '27'=>'千葉県',//銚子
    '28'=>'三重県',//津
    '29'=>'静岡県',//静岡
    '30'=>'東京都',//東京
    '31'=>'神奈川県',//横浜
    '32'=>'島根県',//松江
    '33'=>'鳥取県',//鳥取
    '34'=>'京都府',//京都
    '35'=>'滋賀県',//彦根
    '36'=>'山口県',//下関
    '37'=>'広島県',//広島
    '38'=>'岡山県',//岡山
    '39'=>'兵庫県',//神戸
    '40'=>'大阪府',//大阪
    '41'=>'和歌山県',//和歌山
    '42'=>'奈良県',//奈良
    '43'=>'福岡県',//福岡
    '44'=>'長崎県',//長崎
    '45'=>'佐賀県',//佐賀
    '46'=>'大分県',//大分
    '47'=>'熊本県',//熊本
    '48'=>'鹿児島県',//鹿児島
    '49'=>'宮崎県',//宮崎
    '50'=>'愛媛県',//松山
    '51'=>'香川県',//高松
    '52'=>'高知県',//高知
    '53'=>'徳島県',//徳島
    '56'=>'沖縄県',//那覇
);
$config['search_hokkaido_area'] = array
(
    array('稚内市','1'),
    array('猿払村','1'),
    array('浜頓別町','1'),
    array('中頓別町','1'),
    array('枝幸町','1'),
    array('豊富町','1'),
    array('礼文町','1'),
    array('利尻町','1'),
    array('利尻富士町','1'),
    array('幌延町','1'),
    array('留萌市','1'),
    array('増毛町','1'),
    array('小平町','1'),
    array('苫前町','1'),
    array('羽幌町','1'),
    array('初山別村','1'),
    array('遠別町','1'),
    array('天塩町','1'),
    array('旭川市','2'),
    array('士別市','2'),
    array('名寄市','2'),
    array('富良野市','2'),
    array('鷹栖町','2'),
    array('東神楽町','2'),
    array('当麻町','2'),
    array('比布町','2'),
    array('愛別町','2'),
    array('上川町','2'),
    array('東川町','2'),
    array('美瑛町','2'),
    array('上富良野町','2'),
    array('中富良野町','2'),
    array('南富良野町','2'),
    array('占冠村','2'),
    array('和寒町','2'),
    array('剣淵町','2'),
    array('下川町','2'),
    array('美深町','2'),
    array('音威子府村','2'),
    array('中川町','2'),
    array('幌加内町','2'),
    array('紋別市','3'),
    array('遠軽町','3'),
    array('湧別町','3'),
    array('滝上町','3'),
    array('興部町','3'),
    array('西興部村','3'),
    array('雄武町','3'),
    array('網走市','3'),
    array('美幌町','3'),
    array('津別町','3'),
    array('斜里町','3'),
    array('清里町','3'),
    array('小清水町','3'),
    array('佐呂間町','3'),
    array('大空町','3'),
    array('北見市','3'),
    array('訓子府町','3'),
    array('置戸町','3'),
    array('札幌市中央区','4'),
    array('札幌市北区','4'),
    array('札幌市東区','4'),
    array('札幌市白石区','4'),
    array('札幌市豊平区','4'),
    array('札幌市南区','4'),
    array('札幌市西区','4'),
    array('札幌市厚別区','4'),
    array('札幌市手稲区','4'),
    array('札幌市清田区','4'),
    array('江別市','4'),
    array('千歳市','4'),
    array('恵庭市','4'),
    array('北広島市','4'),
    array('石狩市','4'),
    array('当別町','4'),
    array('新篠津村','4'),
    array('夕張市','4'),
    array('岩見沢市','4'),
    array('美唄市','4'),
    array('芦別市','4'),
    array('赤平市','4'),
    array('三笠市','4'),
    array('滝川市','4'),
    array('砂川市','4'),
    array('歌志内市','4'),
    array('深川市','4'),
    array('南幌町','4'),
    array('奈井江町','4'),
    array('上砂川町','4'),
    array('由仁町','4'),
    array('長沼町','4'),
    array('栗山町','4'),
    array('月形町','4'),
    array('浦臼町','4'),
    array('新十津川町','4'),
    array('妹背牛町','4'),
    array('秩父別町','4'),
    array('雨竜町','4'),
    array('北竜町','4'),
    array('沼田町','4'),
    array('小樽市','4'),
    array('島牧村','4'),
    array('寿都町','4'),
    array('黒松内町','4'),
    array('蘭越町','4'),
    array('ニセコ町','4'),
    array('真狩村','4'),
    array('留寿都村','4'),
    array('喜茂別町','4'),
    array('京極町','4'),
    array('倶知安町','4'),
    array('共和町','4'),
    array('岩内町','4'),
    array('泊村','4'),
    array('神恵内村','4'),
    array('積丹町','4'),
    array('古平町','4'),
    array('仁木町','4'),
    array('余市町','4'),
    array('赤井川村','4'),
    array('帯広市','5'),
    array('音更町','5'),
    array('士幌町','5'),
    array('上士幌町','5'),
    array('鹿追町','5'),
    array('新得町','5'),
    array('清水町','5'),
    array('芽室町','5'),
    array('中札内村','5'),
    array('更別村','5'),
    array('大樹町','5'),
    array('広尾町','5'),
    array('幕別町','5'),
    array('池田町','5'),
    array('豊頃町','5'),
    array('本別町','5'),
    array('足寄町','5'),
    array('陸別町','5'),
    array('浦幌町','5'),
    array('根室市','6'),
    array('別海町','6'),
    array('中標津町','6'),
    array('標津町','6'),
    array('羅臼町','6'),
    array('釧路市','6'),
    array('釧路町','6'),
    array('厚岸町','6'),
    array('浜中町','6'),
    array('標茶町','6'),
    array('弟子屈町','6'),
    array('鶴居村','6'),
    array('白糠町','6'),
    array('室蘭市','7'),
    array('苫小牧市','7'),
    array('登別市','7'),
    array('伊達市','7'),
    array('豊浦町','7'),
    array('壮瞥町','7'),
    array('白老町','7'),
    array('厚真町','7'),
    array('洞爺湖町','7'),
    array('安平町','7'),
    array('むかわ町','7'),
    array('日高町','7'),
    array('平取町','7'),
    array('新冠町','7'),
    array('浦河町','7'),
    array('様似町','7'),
    array('えりも町','7'),
    array('新ひだか町','7'),
    array('函館市','8'),
    array('北斗市','8'),
    array('松前町','8'),
    array('福島町','8'),
    array('知内町','8'),
    array('木古内町','8'),
    array('七飯町','8'),
    array('鹿部町','8'),
    array('森町','8'),
    array('八雲町','8'),
    array('長万部町','8'),
    array('江差町','8'),
    array('上ノ国町','8'),
    array('厚沢部町','8'),
    array('乙部町','8'),
    array('奥尻町','8'),
    array('今金町','8'),
    array('せたな町','8')
);

//特別な鹿児島、名瀬
$config['search_kagoshima_area'] = array
(
    array('奄美市','54'),
    array('十島村','54'),
    array('大和村','54'),
    array('宇検村','54'),
    array('瀬戸内町','54'),
    array('龍郷町','54'),
    array('喜界町','54'),
    array('徳之島町','54'),
    array('天城町','54'),
    array('伊仙町','54'),
    array('和泊町','54'),
    array('知名町','54'),
    array('与論町','54')
);

//特別な沖縄、石垣島、南大東島
$config['search_okinawa_area'] = array
(
    array('石垣市','55'),
    array('竹富町','55'),
    array('与那国町','55'),
    array('宮古島市','55'),
    array('多良間村','55'),
    array('南大東村','57'),
    array('北大東村','57'),
);

//特別な東京、父島
$config['search_tokyo_area'] = array
(
    array('小笠原村','58'),
    array('三宅村','58'),
    array('御蔵島村','58'),
    array('八丈町','58'),
    array('青ヶ島村','58'),
    array('大島町','58'),
    array('利島村','58'),
    array('新島村','58'),
    array('神津島村','58')
);
/* End of file config.php */
/* Location: ./application/config/config.php */
